[package]
name = "kamipad_server"
version = "0.1.0"
edition = "2021"

# Reference: https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.0" }
tokio = { version = "1.0", features = ["full"]}
warp = { version = "0.3" }
